name: .NET Obfuscator CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore NuGet Packages
      # Specify the path to your solution file here
      run: dotnet restore DotNetObfuscator/DotNetObfuscator.sln 

    - name: Build Project
      # Specify the path to your solution file here as well
      run: dotnet build DotNetObfuscator/DotNetObfuscator.sln --configuration Release --no-restore 

    # Optional: If you have unit tests, specify the path to your test project
    # - name: Run Tests
    #   run: dotnet test DotNetObfuscator.Tests/DotNetObfuscator.Tests.csproj --configuration Release --no-build --verbosity normal
