name: .NET Obfuscator Build

on:
  push:
    branches: [ "master", "main" ] # Trigger on pushes to master or main branches
  pull_request:
    branches: [ "master", "main" ] # Trigger on pull requests targeting master or main

jobs:
  build:
    runs-on: windows-latest # Using a Windows runner as .NET projects often work well here

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4 # Action to install a specific .NET SDK version
      with:
        dotnet-version: '8.x' # Specify the desired .NET version (e.g., '6.x', '7.x', '8.x')

    - name: Restore NuGet packages
      run: dotnet restore # Restore project dependencies from NuGet

    - name: Build Project
      run: dotnet build --configuration Release --no-restore # Build the project in Release configuration
      # If your solution file is not in the root, specify the path:
      # run: dotnet build YourSolutionFolder/YourSolution.sln --configuration Release --no-restore

    # Uncomment the following steps if your project has tests and you want to run them
    # - name: Run Tests
    #   run: dotnet test --configuration Release --no-build --verbosity normal
    #   # If your test project is not in the root, specify the path:
    #   # run: dotnet test YourTestsFolder/YourTests.csproj --configuration Release --no-build --verbosity normal
